### ISSUE TITLE
css2xpath doesn't support next sibling selector

### ISSUE THREAD

**Issue by Ivanca** [rc0x03/node-libxmljs-dom#2]
The following selector doesn't work because css2xpath.js doesn't properly convert it

```
td:contains("name") + td
```

css2xpath is [unmaintained](https://code.google.com/p/css2xpath/) so better use this one: https://github.com/featurist/css-to-xpath

BTW I just find another bug in css2xpath... the regular expressions (such as `[a-zA-Z0-9\_\-\*]`) are all wrong because most ut8 characters are valid CSS selectors, heck! you can even use emoji as [css selectors](http://codepen.io/team/redbubble/pen/QjNyaO).
# 

A workaround in the mean time is to use xpath directly:

```
td:contains("name")/following-sibling::td
```

**Comment by rc0x03** [comment]
The following sibling selector is working fine for me.

`li:contains("first") + li`

converts to

`.//li[contains(normalize-space(),"first")]/following-sibling::*[1]/self::li`
