### ISSUE TITLE
Critical issue: Storage.js doesn't exist

### ISSUE THREAD

**Issue by Ivanca** [rc0x03/node-libxmljs-dom#3]
**Window.js** is referencing 2 files that don't exist (`./Storage.js` and `./HttpRequest.js`)
Code at: https://github.com/rc0x03/node-libxmljs-dom/blob/master/lib/Window.js#L7

Please be more careful, maybe some sort of tests would help to prevent this kind of issues?

**Comment by Ivanca** [comment]
If anyone else has this problem (meaning any installation since yesterday), because there wasn't a version bump after this breaking change you can use a commit number on your dependency in your package.json file
```
"dependencies" : {
    "libxmljs-dom": "git://github.com/rc0x03/node-libxmljs-dom.git#f13f862d119b5bb41c42e42207d3367509b26391"
}
```

**Comment by rc0x03** [comment]
This project is still in early development and I'm still in the process of building a test suite. This means that the only dependable version is the one on NPM. A more reliable option would be to use the NPM version instead.

```javascript
    "dependencies": {
        "libxmljs-dom": ">=0.0.2"
    }
```

**Comment by Ivanca** [comment]
...yeah, **except that this issue happens when installing from npm**.

And this doesn't need a test suite, a simple script that tried to install the module would have catched this error
