### ISSUE TITLE
Please don't auto-publish to NPM without version bump

### ISSUE THREAD

**Issue by Ivanca** [rc0x03/node-libxmljs-dom#4]
A week ago I had

```
"dependencies": {
    "osmosis": "0.1.0",
    "libxmljs-dom": "0.0.2"
}
```

And today I deleted node_modules and did an "npm install" and the very same code stopped working, why? Very likely you are auto-publishing the current version to NPM.

The code that used to work was `form.find('[name]')[0].name()` but your current version uses `.nodeValue` instead so the .submit method on promises.js (osmosis) stopped working, and worse of all fails 100% silently, no even .error(console.log) catches it.

I can bounty/donate 50 bucks if you just sort this out, meaning that versions should be static, "libxmljs-dom": "0.0.2" a week from now should be exactly the same on NPM, if you need to fix something no matter how critical just bump the version (e.g. 0.0.3).

Thank you very much for your work.

**Comment by rc0x03** [comment]
Great suggestion. This is especially important with the instability of the `libxmljs-dom` internal API. The next version of Osmosis will use a static `libxmljs-dom` version instead. I'll close this issue once the next versions are released.

**Comment by rc0x03** [comment]
Fixed in latest versions
